version: '3'
services:
  web:
    build: .
    ports:
      - "8050:8050"
    environment:
      - DB_URL=postgresql://user:pass@db:5432/fundos
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: fundos
    ports:
      - "5432:5432"
